// <auto-generated />
using System;
using Gelecek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gelecek.Migrations
{
    [DbContext(typeof(ZamanContext))]
    [Migration("20201026201208_notunıqe")]
    partial class notunıqe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Gelecek.Models.Posta", b =>
                {
                    b.Property<int>("PostaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("IletilecekZaman")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("varchar(7000)");

                    b.Property<string>("MetinKonusu")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NeZamanYazildi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostaAdresi")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("PostaId");

                    b.HasIndex("UyeId");

                    b.ToTable("TblPostalar");
                });

            modelBuilder.Entity("Gelecek.Models.Uye", b =>
                {
                    b.Property<int>("Uyeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.HasKey("Uyeid");

                    b.ToTable("TblUyeler");
                });

            modelBuilder.Entity("Gelecek.Models.Posta", b =>
                {
                    b.HasOne("Gelecek.Models.Uye", "Kullanici")
                        .WithMany("GonderilenPostalar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Gelecek.Models.Uye", b =>
                {
                    b.Navigation("GonderilenPostalar");
                });
#pragma warning restore 612, 618
        }
    }
}
