// <auto-generated />
using System;
using Gelecek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gelecek.Migrations
{
    [DbContext(typeof(ZamanContext))]
    partial class ZamanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Gelecek.Models.Posta", b =>
                {
                    b.Property<int>("Postaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("PostaAdresi")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<int>("Uyeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("iletilecekZaman")
                        .HasColumnType("datetime2");

                    b.Property<string>("metin")
                        .IsRequired()
                        .HasColumnType("varchar(7000)");

                    b.Property<string>("metinKonusu")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("nezamanYazildi")
                        .HasColumnType("datetime2");

                    b.HasKey("Postaid");

                    b.HasIndex("Uyeid");

                    b.ToTable("TblPostalar");
                });

            modelBuilder.Entity("Gelecek.Models.Uye", b =>
                {
                    b.Property<int>("Uyeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.HasKey("Uyeid");

                    b.HasAlternateKey("Eposta");

                    b.ToTable("TblUyeler");
                });

            modelBuilder.Entity("Gelecek.Models.Posta", b =>
                {
                    b.HasOne("Gelecek.Models.Uye", "Kullanici")
                        .WithMany("gonderilenPostalar")
                        .HasForeignKey("Uyeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Gelecek.Models.Uye", b =>
                {
                    b.Navigation("gonderilenPostalar");
                });
#pragma warning restore 612, 618
        }
    }
}
